version: '3'

services:
  postgres:
    image: 'postgres:10'
    container_name: 'postgresql'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_DB=cloud_storage_db'
    volumes:
      - ./src/main/java/com/vianny/cloudstorageapi/sql/database.sql:/docker-entrypoint-initdb.d/database.sql

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    environment:
      - 'MINIO_ACCESS_KEY: minioadmin'
      - 'MINIO_SECRET_KEY: minioadmin'
    volumes:
      - /mnt/minio/data:/data
    command: server /data

  java-app:
    build: ./
    container_name: 'cloudStorage'
    ports:
    - "8080:8080"